[build]
  command = "cp next.config.netlify.js next.config.js && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Disable processing for Next.js
[build.processing]
  skip_processing = true